name: atlan_demo
description: A flutter application for Atlan.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  logger: ^0.7.0+2
  dotted_border: ^1.0.2
  intl: ^0.15.8
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6+3
  provider: ^3.0.0+1
  flutter_svg: ^0.14.0
  flutter_rating_bar: ^2.0.0+2
  grouped_buttons: ^1.0.4
  uuid: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/atlan.svg
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Black.ttf
        - asset: assets/fonts/NunitoSans-BlackItalic.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
        - asset: assets/fonts/NunitoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/NunitoSans-Light.ttf
        - asset: assets/fonts/NunitoSans-LightItalic.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf